language: generic

before_install:
  - openssl aes-256-cbc -K $encrypted_7aa7c07064dd_key -iv $encrypted_7aa7c07064dd_iv
    -in $TRAVIS_BUILD_DIR/travis-git.enc -out ~\/.ssh/travis-git -d

deploy:
- provider: script
  skip_cleanup: true
  script: "$TRAVIS_BUILD_DIR/deploy.sh"
  on:
    branch: master


